name: Domain DeÄŸiÅŸiklik KontrolÃ¼
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron: 25 */6 * * *
jobs:
  DomainKontrol:
    runs-on: ubuntu-latest
    env:
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Depo KontrolÃ¼
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DOMAINTOKEN }}  

      - name: Python 3.11.8 YÃ¼kle
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.8

      - name: Python SÃ¼rÃ¼mÃ¼nÃ¼ GÃ¶ster
        run: python -c "import sys; print(sys.version)"

      - name: Gereksinimleri YÃ¼kle
        run: |
              python -m pip install --upgrade pip
              pip install -U setuptools wheel cloudscraper pycryptodome Kekik


      - name: BetiÄŸi Ã‡alÄ±ÅŸtÄ±r
        run: python KONTROL.py

      - name: DeÄŸiÅŸiklik KontrolÃ¼
        id: degisiklik_kontrol
        run: |
          git diff --quiet . || echo "degisiklik=true" >> $GITHUB_OUTPUT || true

      - name: DeÄŸiÅŸiklikleri Push Et
        if: steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add -A
          
          git commit -m " Domain DeÄŸiÅŸikliÄŸi" \
            -m "ğŸ”„ Otomatik domain gÃ¼ncellemeleri yapÄ±ldÄ±."
          
          git push origin master
